<img
className="Gap"
src={require("../images/product/Group1.svg")}
alt="Drop"
/>
<img
className="Gap"
src={require("../images/product/Group3.svg")}
alt="Drop"
/>
</div>
<div className="ImageGap">
<img
className="Gap"
src={require("../images/product/Group2.svg")}
alt="Drop"
/>
<img
className="Gap"
src={require("../images/product/Group4.svg")}
alt="Drop"
/>
</div>